# Generated by Django 4.0 on 2021-12-14 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Подразделение')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия ')),
                ('patronymic', models.CharField(max_length=150, verbose_name='Отчество')),
                ('employment_start_date', models.DateField(verbose_name='Дата')),
                ('employment_department', models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='employee.department', verbose_name='Подразделение')),
                ('employment_position', models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='employee.position', verbose_name='Должность')),
            ],
        ),
    ]
